package Calculadora;
/**
 *
 * @author Vini
 */
public class Calculadora extends javax.swing.JFrame {

    public static String calc;
    public static float num1;
    public static float num2;
    public static float resultado;

    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tag = new javax.swing.JLabel();
        txtResultado = new javax.swing.JTextField();
        limpar = new javax.swing.JButton();
        raiz = new javax.swing.JButton();
        potencia = new javax.swing.JButton();
        divisao = new javax.swing.JButton();
        button7 = new javax.swing.JButton();
        button8 = new javax.swing.JButton();
        button9 = new javax.swing.JButton();
        multiplicacao = new javax.swing.JButton();
        button4 = new javax.swing.JButton();
        button5 = new javax.swing.JButton();
        button6 = new javax.swing.JButton();
        subtracao = new javax.swing.JButton();
        button1 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        adicao = new javax.swing.JButton();
        button0 = new javax.swing.JButton();
        ponto = new javax.swing.JButton();
        apagarUm = new javax.swing.JButton();
        igual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tag.setBackground(new java.awt.Color(255, 255, 255));
        tag.setFont(new java.awt.Font("Digital-7 Mono", 0, 42)); // NOI18N
        tag.setForeground(new java.awt.Color(51, 51, 255));
        tag.setText("9 9 9");
        getContentPane().add(tag, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 100, 40));

        txtResultado.setEditable(false);
        txtResultado.setBackground(new java.awt.Color(48, 169, 47));
        txtResultado.setFont(new java.awt.Font("Digital-7 Mono", 0, 40)); // NOI18N
        txtResultado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtResultado.setToolTipText("result");
        txtResultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtResultado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultadoActionPerformed(evt);
            }
        });
        getContentPane().add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 270, 70));

        limpar.setText("C");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });
        getContentPane().add(limpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 60, 50));

        raiz.setText("√");
        raiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raizActionPerformed(evt);
            }
        });
        getContentPane().add(raiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 60, 50));

        potencia.setText("x²");
        potencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potenciaActionPerformed(evt);
            }
        });
        getContentPane().add(potencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 60, 50));

        divisao.setText("÷");
        divisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisaoActionPerformed(evt);
            }
        });
        getContentPane().add(divisao, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 60, 50));

        button7.setText("7");
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });
        getContentPane().add(button7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 60, 50));

        button8.setText("8");
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });
        getContentPane().add(button8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 60, 50));

        button9.setText("9");
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });
        getContentPane().add(button9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 60, 50));

        multiplicacao.setText("X");
        multiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicacaoActionPerformed(evt);
            }
        });
        getContentPane().add(multiplicacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 60, 50));

        button4.setText("4");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        getContentPane().add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 60, 50));

        button5.setText("5");
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        getContentPane().add(button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 60, 50));

        button6.setText("6");
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });
        getContentPane().add(button6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 60, 50));

        subtracao.setText("-");
        subtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtracaoActionPerformed(evt);
            }
        });
        getContentPane().add(subtracao, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 60, 50));

        button1.setText("1");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 60, 50));

        button2.setText("2");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        getContentPane().add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 60, 50));

        button3.setText("3");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        getContentPane().add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 60, 50));

        adicao.setText("+");
        adicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicaoActionPerformed(evt);
            }
        });
        getContentPane().add(adicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 60, 50));

        button0.setText("0");
        button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button0ActionPerformed(evt);
            }
        });
        getContentPane().add(button0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 60, 50));

        ponto.setText(".");
        ponto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pontoActionPerformed(evt);
            }
        });
        getContentPane().add(ponto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 60, 50));

        apagarUm.setBackground(new java.awt.Color(255, 51, 51));
        apagarUm.setForeground(new java.awt.Color(255, 255, 255));
        apagarUm.setText("-1");
        apagarUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagarUmActionPerformed(evt);
            }
        });
        getContentPane().add(apagarUm, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 60, 50));

        igual.setText("=");
        igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualActionPerformed(evt);
            }
        });
        getContentPane().add(igual, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 60, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultadoActionPerformed

    }//GEN-LAST:event_txtResultadoActionPerformed

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        txtResultado.setText(" ");
        calc = "zero";
        num1 = 0;
        num2 = 0;
    }//GEN-LAST:event_limparActionPerformed

    private void raizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raizActionPerformed
        double num1 = Double.valueOf(txtResultado.getText());
        double resultado = Math.sqrt((double) (num1));
        String resultadoString = String.valueOf(resultado);
        txtResultado.setText(resultadoString);

    }//GEN-LAST:event_raizActionPerformed

    private void potenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potenciaActionPerformed
        Float num1 = Float.valueOf(txtResultado.getText());
        resultado = num1 * num1;
        String resultadoString = String.valueOf(resultado);
        txtResultado.setText(resultadoString);
    }//GEN-LAST:event_potenciaActionPerformed

    private void divisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisaoActionPerformed
        Float num1 = Float.valueOf(txtResultado.getText());
        calc = "dividir";
        num2 = num1;
        txtResultado.setText("");
    }//GEN-LAST:event_divisaoActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        txtResultado.setText(txtResultado.getText() + "7");
    }//GEN-LAST:event_button7ActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
        txtResultado.setText(txtResultado.getText() + "8");
    }//GEN-LAST:event_button8ActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
        txtResultado.setText(txtResultado.getText() + "9");
    }//GEN-LAST:event_button9ActionPerformed

    private void multiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicacaoActionPerformed
        Float num1 = Float.valueOf(txtResultado.getText());
        calc = "multiplicar";
        num2 = num1;
        txtResultado.setText("");
    }//GEN-LAST:event_multiplicacaoActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        txtResultado.setText(txtResultado.getText() + "4");
    }//GEN-LAST:event_button4ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        txtResultado.setText(txtResultado.getText() + "5");
    }//GEN-LAST:event_button5ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        txtResultado.setText(txtResultado.getText() + "6");
    }//GEN-LAST:event_button6ActionPerformed

    private void subtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtracaoActionPerformed
        Float num1 = Float.valueOf(txtResultado.getText());
        calc = "subtrair";
        num2 = num1;
        txtResultado.setText("");
    }//GEN-LAST:event_subtracaoActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        txtResultado.setText(txtResultado.getText() + "1");
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        txtResultado.setText(txtResultado.getText() + "2");
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        txtResultado.setText(txtResultado.getText() + "3");
    }//GEN-LAST:event_button3ActionPerformed

    private void adicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicaoActionPerformed
        Float num1 = Float.valueOf(txtResultado.getText());
        calc = "adicao";
        num2 = num1;
        txtResultado.setText("");
    }//GEN-LAST:event_adicaoActionPerformed

    private void button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button0ActionPerformed
        txtResultado.setText(txtResultado.getText() + "0");
    }//GEN-LAST:event_button0ActionPerformed

    private void pontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pontoActionPerformed
        txtResultado.setText(txtResultado.getText() + ".");
    }//GEN-LAST:event_pontoActionPerformed

    private void apagarUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagarUmActionPerformed
        String tira = txtResultado.getText();
        tira = tira.substring(0, tira.length() - 1);
        txtResultado.setText(tira);
    }//GEN-LAST:event_apagarUmActionPerformed

    private void igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualActionPerformed
        if (calc.equals("adicao")) {
            Float num1 = Float.valueOf(txtResultado.getText());
            resultado = num2 + num1;
            String resultadoString = String.valueOf(resultado);
            txtResultado.setText(resultadoString);
        } else if (calc.equals("subtrair")) {
            Float num1 = Float.valueOf(txtResultado.getText());
            resultado = num2 - num1;
            String resultadoString = String.valueOf(resultado);
            txtResultado.setText(resultadoString);
        } else if (calc.equals("multiplicar")) {
            Float num1 = Float.valueOf(txtResultado.getText());
            resultado = num2 * num1;
            String resultadoString = String.valueOf(resultado);
            txtResultado.setText(resultadoString);
        } else if (calc.equals("dividir")) {
            Float num1 = Float.valueOf(txtResultado.getText());
            resultado = num2 / num1;
            String resultadoString = String.valueOf(resultado);
            txtResultado.setText(resultadoString);
        }
    }//GEN-LAST:event_igualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicao;
    private javax.swing.JButton apagarUm;
    private javax.swing.JButton button0;
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JButton button5;
    private javax.swing.JButton button6;
    private javax.swing.JButton button7;
    private javax.swing.JButton button8;
    private javax.swing.JButton button9;
    private javax.swing.JButton divisao;
    private javax.swing.JButton igual;
    private javax.swing.JButton limpar;
    private javax.swing.JButton multiplicacao;
    private javax.swing.JButton ponto;
    private javax.swing.JButton potencia;
    private javax.swing.JButton raiz;
    private javax.swing.JButton subtracao;
    private javax.swing.JLabel tag;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
